---
- hosts: production

  pre_tasks:
    - name: Include vars of apps
      include_vars:
        file: apps.yml
        name: apps

  tasks:
    - name: System dependencies
      include_tasks: "system.yml"

    - name: System user 
      include_tasks: "user.yml"
      vars:
          user: "{{ item.user }}"
          password: "{{ item.password | password_hash('md5') }}"
      when: item.user and item.password
      with_items: "{{ apps[inventory_hostname] }}"

    - name: Apache PHP
      vars:
        domain: "{{ loop_item.domain }}"
        user: "{{ loop_item.user }}"
        address: "{{ loop_item.address }}"
      include_role:
        name: ezyatev.apache-php
      when: loop_item.install_apache_php == 'y' and domain and user and loop_item.password
      with_items: "{{ apps[inventory_hostname] }}"
      loop_control:
        loop_var: loop_item
    
    - name: PHP-FPM
      vars:
        domain: "{{ loop_item.domain }}"
        user: "{{ loop_item.user }}"
        address: "{{ loop_item.address }}"
        php_fpm_pool_name: "{{ loop_item.php_fpm_pool_name }}"
        php_fpm_pool_listen: "{{ loop_item.php_fpm_pool_listen }}"
      include_role:
        name:  nbz4live.php-fpm
      when: loop_item.install_nginx_php == 'y' and domain and user and loop_item.password
      with_items: "{{ apps[inventory_hostname] }}"
      loop_control:
        loop_var: loop_item
    
    - name: Nginx PHP
      vars:
        domain: "{{ loop_item.domain }}"
        user: "{{ loop_item.user }}"
        address: "{{ loop_item.address }}"
        php_fpm_pool_listen: "{{ loop_item.php_fpm_pool_listen }}"
      include_role:
        name: jdauphant.nginx
      when: loop_item.install_nginx_php == 'y' and domain and user and loop_item.password
      with_items: "{{ apps[inventory_hostname] }}"
      loop_control:
        loop_var: loop_item

    - name: PHP Composer
      include_role:
        name: geerlingguy.composer
      when: loop_item.install_composer == 'y' and loop_item.user and loop_item.password
      with_items: "{{ apps[inventory_hostname] }}"
      loop_control:
        loop_var: loop_item

    - name: MySQL
      vars:
        mysql_user: "{{ loop_item.mysql_user }}"
        mysql_db: "{{ loop_item.mysql_db }}"
        mysql_password: "{{ loop_item.mysql_password }}"
      include_role:
        name: geerlingguy.mysql
      when: loop_item.install_mysql == 'y' and mysql_db and mysql_user and mysql_password
      with_items: "{{ apps[inventory_hostname] }}"
      loop_control:
        loop_var: loop_item

    - name: NodeJS
      include_role:
        name: gotansible.nodejs
      when: loop_item.install_grunt == 'y' and loop_item.user and loop_item.password
      with_items: "{{ apps[inventory_hostname] }}"
      loop_control:
        loop_var: loop_item

    - name: RubyGems
      include_role:
        name: AsianChris.rubygems
      when: loop_item.install_grunt == 'y' and loop_item.user and loop_item.password
      with_items: "{{ apps[inventory_hostname] }}"
      loop_control:
        loop_var: loop_item

    - name: NPM
      include_role:
        name: manala.npm
      when: loop_item.install_grunt == 'y' and loop_item.user and loop_item.password
      with_items: "{{ apps[inventory_hostname] }}"
      loop_control:
        loop_var: loop_item

    - name: Webserver
      include_tasks: "webserver.yml"
      vars:
          user: "{{ item.user }}"
          domain: "{{ item.domain }}"
          install_apache_php: "{{ item.install_apache_php }}"
          install_nginx_php: "{{ item.install_nginx_php }}"
      when: item.domain and user and item.password
      with_items: "{{ apps[inventory_hostname] }}"

    - name: Grunt 
      include_tasks: "grunt.yml"
      vars:
          user: "{{ item.user }}"
      when: item.install_grunt == 'y' and item.user and item.password
      with_items: "{{ apps[inventory_hostname] }}"
